### ISSUE TITLE
bug in install.sh

### ISSUE THREAD

**Issue by fermigas** [hugo-dc/wpm#1]
5   if [ ! -d "$BIN_DIR" ]; then 
6     mkdir $BIN_DIR
7     echo "Adding $BIN_DIR to your PATH..." 
8      echo "export PATH=$PATH:$BINDIR" >> $HOME/.bahsrc
9     source $HOME/.bashrc
10  fi

Line 8 misspells ".bashrc"  as ".bahsrc"

**Comment by hugo-dc** [comment]
Thank You, I've fixed it.
